### ISSUE TITLE
moving out from osrtools-legacy

### ISSUE THREAD

**Issue by bemxio** [Plextora/osr-name#1]
hi plextora!
i recently worked on dumping now and now i made a fork of `osrparse`, that has support for all game modes!
everything is now working nicely

just saying that you should move into [the fork](https://github.com/bemxio/osu-replay-parser/tree/dumping) in this repo
you can easily install the fork into `pip` by uninstalling the original `osrparse` and installing the fork:
```sh
pip uninstall osrparse
pip install git+https://github.com/bemxio/osu-replay-parser@dumping
```

all instructions are in the README of the branch!
i also made a PR to the original repo, so it might be eventually moved into the original `osrparse` itself

**Comment by Plextora** [comment]
Hello bemxio,

I just finished moving into the fork [in this commit.](https://github.com/Plextora/osr-name/commit/a0de92184509819025a6483752a417fe891d6a96)

Thanks for telling me about this.
