### ISSUE TITLE
dumping merged into osrparse

### ISSUE THREAD

**Issue by bemxio** [Plextora/osr-name#2]
hello once again plextora!
dumping was successfully merged into the main `osrparse` library, with just a little change!
now, to dump the replay, you need to call the `.dump(file_path)` function in the `Replay` class itself!
so, something like:
```py
import osrparse

replay = osrparse.parse_replay_file("path/to/osr.osr")
replay.dump("path/to/new_osr.osr")
```

(P.S. remember to change the readme about the module to install this time! haha)

**Comment by Plextora** [comment]
Hello bemxio!

I just finished moving osr!name to the main `osrparse` library in [this commit](https://github.com/Plextora/osr-name/commit/76d0d8cc3788472ad3f320691f84dd1544c5c4d5)

(Thanks for the P.S at the end! I probably would've forgot to update the REAMDE.md again! 😅)
